name:                amqp-streamly
version:             0.1.0
github:              "blackheaven/amqp-streamly"
license:             BSD3
author:              "Gautier DI FOLCO"
maintainer:          "gautier.difolco@gmail.com"
copyright:           "Gautier DI FOLCO"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simpler streamly wrapper for amqp
category:            streamly, conduit

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/blackheaven/amqp-streamly#readme>

dependencies:
- base >= 4.7 && < 5
- amqp >= 0.19.1 && < 0.20
- streamly >= 0.7.2 && < 0.8
- text >= 1.2.4.0 && < 1.3

library:
  source-dirs: src

tests:
  amqp-streamly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amqp-streamly
    - bytestring >= 0.10.10.0 && < 0.11
    - hspec >= 2.7.1 && < 2.8
    - docker >= 0.6.0.4 && < 0.7
