name:                amqp-streamly
version:             0.2.0
github:              "blackheaven/amqp-streamly"
license:             BSD3
author:              "Gautier DI FOLCO"
maintainer:          "gautier.difolco@gmail.com"
copyright:           "Gautier DI FOLCO"
description:         A simple streamly wrapper for amqp. Provides two functions `produce` and `consume`.

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple streamly wrapper for amqp
category:            streamly, conduit, amqp, rabbitmq

dependencies:
- base >= 4.7 && < 5
- amqp >= 0.19.1 && < 0.21
- streamly >= 0.7.2 && < 0.8
- text >= 1.2.4.0 && < 1.3

library:
  source-dirs: src

tests:
  amqp-streamly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amqp-streamly
    - bytestring >= 0.10.10.0 && < 0.11
    - hspec >= 2.7.1 && < 2.8
    - process >= 1.6.8.0 && < 1.7
    - testcontainers == 0.1.*
