name:                amqp-streamly
version:             0.2.1
github:              "blackheaven/amqp-streamly"
license:             BSD3
author:              "Gautier DI FOLCO"
maintainer:          "gautier.difolco@gmail.com"
copyright:           "Gautier DI FOLCO"
description:         A simple streamly wrapper for amqp. Provides two functions `produce` and `consume`.

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple streamly wrapper for amqp
category:            streamly, conduit, amqp, rabbitmq

dependencies:
- base
- amqp
- streamly
- text

library:
  source-dirs: src

tests:
  amqp-streamly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amqp-streamly
    - bytestring
    - hspec
    - process
    - testcontainers
